
mutation AskChatQuestion(
    $copilotId: UUID!
    $question: String!
    $threadId: UUID
    $skipReportCache: Boolean
    $dryRunType: ChatDryRunType
) {
    askChatQuestion(
        copilotId: $copilotId,
        question: $question,
        threadId: $threadId
        skipReportCache: $skipReportCache
        dryRunType: $dryRunType
    ) {
        id
        threadId
        answer {
            ...ChatResultFragment
        }
    }
}

mutation QueueChatQuestion(
    $threadId: UUID!
    $question: String!
    $skipCache: Boolean
) {
    queueChatQuestion(
        threadId: $threadId,
        question: $question,
        skipCache: $skipCache,
    ) {
        threadId
        id
    }
}

fragment ChatResultFragment on MaxChatResult {
    answerId
    answeredAt
    copilotSkillId
    hasFinished
    error
    isNewThread
    message
    reportResults {
        id
        title
        reportName
        runId
        parameters {
            key
            values
            label
        }
        contentBlocks {
            id
            title
            payload
        }
    }
    threadId
    userId
}

mutation CancelChatQuestion(
    $entryId: UUID!
) {
    cancelChatQuestion(entryId: $entryId) {
        threadId
        id
    }
}

query ChatEntry(
    $id: UUID!
) {
    chatEntry(id: $id) {
        id
        threadId
        answer {
            ...ChatResultFragment
        }
    }
}

query ChatThread($id: UUID!) {
    chatThread(id: $id) {
        id
        entryCount
        title
        copilotId
        entries {
            ...ChatResultFragment
        }
    }
}

mutation CreateChatThread($copilotId: UUID!) {
    createChatThread(copilotId: $copilotId) {
        id
        copilotId
    }
}