query GetMaxLlmPrompt(
    $llmPromptId: UUID!,
    $templateVariables: JSON,
    $kShotCount: Int,
    $kShotThreshold: Int,
    $kShotMatch: String
) {
    getMaxLlmPrompt(llmPromptId: $llmPromptId, templateVariables: $templateVariables, kShotCount: $kShotCount, kShotThreshold: $kShotThreshold, kShotMatch: $kShotMatch) {
        llmPromptId
        name
    }
}
