query GetCopilotSkill($copilotId: UUID!, $copilotSkillId: UUID!, $usePublishedVersion: Boolean) {
    getCopilotSkill(copilotId: $copilotId, copilotSkillId: $copilotSkillId, usePublishedVersion: $usePublishedVersion) {
        copilotSkillId
        name
        copilotSkillType
        detailedName
        description
        detailedDescription
        datasetId
        skillChatQuestions {
            copilotSkillChatQuestionId
            question
            expectedCompletionResponse
        }
        yamlCode
        skillCode
        miscInfo
        schedulingOnly
        copilotSkillNodes {
            copilotSkillNodeId
            skillComponentId
            name
            description
            userData
            nodeConnections {
                inputProperty
                sourceNodeId
                outputProperty
            }
        }
        parameters {
            copilotSkillParameterId
            name
            copilotParameterType
            parameterSourceKey
            isMulti
            metadataField
            llmDescription
            constrainedValues
            value
            description
            isActive
            createdUserId
            createdUtc
            lastModifiedUserId
            lastModifiedUtc
            version
        }
        capabilities
        limitations
        exampleQuestions
        parameterGuidance
    }
}

query GetCopilotInfo($copilotId: UUID!, $usePublishedVersion: Boolean) {
    getCopilotInfo(copilotId: $copilotId, usePublishedVersion: $usePublishedVersion) {
        copilotId
        name
        description
        systemPrompt
        betaYaml
        globalPythonCode
        copilotQuestions
        connectionDatasets
        copilotSkillIds
        copilotTopics
    }
}

query GetCopilots {
    getCopilots {
        copilotId
        name
        description
        systemPrompt
        betaYaml
        globalPythonCode
        copilotQuestions {
            copilotQuestionId
            nl
            skillId
            parameters
            isStarter
            hint
            createdUserId
            createdUtc
            lastModifiedUserId
            lastModifiedUtc
            version
            isDeleted
        }
        connectionDatasets {
            datasetId
            name
        }
        copilotSkillIds
        copilotTopics {
            copilotTopicId
            name
            description
            researchOutline
            presentationOutline
            createdUserId
            createdUserName
            createdUtc
            lastModifiedUserId
            lastModifiedUserName
            lastModifiedUtc
            isActive
        }
        databaseId
        datasetId
    }
}

query GetCopilotHydratedReports($copilotId: UUID!, $overrideDatasetId: UUID, $loadAllSkills: Boolean) {
    getCopilotHydratedReports(copilotId: $copilotId, overrideDatasetId: $overrideDatasetId, loadAllSkills: $loadAllSkills) {
        copilotId
        copilotSkillId
        datasetId
        datasetIds
        detailedDescription
        key
        name
        packageName
        parameters {
            constrainedValues
            definition {
                constraints
                key
                multi
                type
            }
            description
            isHidden
            isMulti
            key
            llmDescription
            metadataField
            skillParamDefKey
            value
            matchValues {
                automaticDbWhitelist
                datasetId
                inverseMap
                phraseTemplate
                popularValues
                valueCollectionName
                datasetDateDimensions
                datasetDimensions
                datasetMetrics
                predicateVocab
            }
        }
        schedulingOnly
        toolDescription
        toolName
        type
        usePredicateFilters
    }
}
