query GetCopilotSkill($copilotId: UUID!, $copilotSkillId: UUID!, $usePublishedVersion: Boolean) {
    getCopilotSkill(copilotId: $copilotId, copilotSkillId: $copilotSkillId, usePublishedVersion: $usePublishedVersion) {
        copilotSkillId
        name
        copilotSkillType
        detailedName
        description
        detailedDescription
        datasetId
        skillChatQuestions {
            copilotSkillChatQuestionId
            question
            expectedCompletionResponse
        }
        yamlCode
        skillCode
        miscInfo
        schedulingOnly
        copilotSkillNodes {
            copilotSkillNodeId
            skillComponentId
            name
            description
            userData
            nodeConnections {
                inputProperty
                sourceNodeId
                outputProperty
            }
        }
    }
}

query GetCopilotInfo($copilotId: UUID!, $usePublishedVersion: Boolean) {
    getCopilotInfo(copilotId: $copilotId, usePublishedVersion: $usePublishedVersion) {
        copilotId
        name
        description
        systemPrompt
        betaYaml
        globalPythonCode
        copilotQuestions
        connectionDatasets
        copilotSkillIds
        copilotTopics
    }
}
