query GetGroundedValue(
  $datasetId: UUID!
  $value: String!
  $domainEntity: String
  $copilotId: UUID
) {
  getGroundedValue(
    datasetId: $datasetId
    value: $value
    domainEntity: $domainEntity
    copilotId: $copilotId
  ) {
    matchedValue
    matchQuality
    matchType
    mappedIndicator
    mappedValue
    preferred
    domainEntity
    otherMatches
  }
}

query GetDataset2(
  $datasetId: UUID!
) {
  getDataset2(
    datasetId: $datasetId
  ) {
    datasetId
    name
    description
    databaseId
    dimensions
    metrics
    miscInfo
    sourceTable
    sourceSql
    dataInterval
    datasetMinDate
    datasetMaxDate
    queryRowLimit
    useDatabaseCasing
    kShotLimit
  }
}

mutation CreateDataset(
  $dataset: JSON!
) {
  createDataset(
    dataset: $dataset
  ) {
    success
    code
    error
  }
}

mutation UpdateDatasetName(
  $datasetId: UUID!
  $name: String!
) {
  updateDatasetName(
    datasetId: $datasetId
    name: $name
  ) {
    success
    code
    error
  }
}

mutation UpdateDatasetDescription(
  $datasetId: UUID!
  $description: String
) {
  updateDatasetDescription(
    datasetId: $datasetId
    description: $description
  ) {
    success
    code
    error
  }
}

mutation UpdateDatasetDateRange(
  $datasetId: UUID!
  $datasetMinDate: DateTime
  $datasetMaxDate: DateTime
) {
  updateDatasetDateRange(
    datasetId: $datasetId
    datasetMinDate: $datasetMinDate
    datasetMaxDate: $datasetMaxDate
  ) {
    success
    code
    error
  }
}

mutation UpdateDatasetMiscInfo(
  $datasetId: UUID!
  $miscInfo: String
) {
  updateDatasetMiscInfo(
    datasetId: $datasetId
    miscInfo: $miscInfo
  ) {
    success
    code
    error
  }
}

mutation CreateDimension(
  $datasetId: UUID!
  $dimension: JSON!
) {
  createDimension(
    datasetId: $datasetId
    dimension: $dimension
  ) {
    success
    code
    error
  }
}

mutation UpdateDimension(
  $datasetId: UUID!
  $dimension: JSON!
) {
  updateDimension(
    datasetId: $datasetId
    dimension: $dimension
  ) {
    success
    code
    error
  }
}

mutation DeleteDimension(
  $datasetId: UUID!
  $dimensionId: String!
) {
  deleteDimension(
    datasetId: $datasetId
    dimensionId: $dimensionId
  ) {
    success
    code
    error
  }
}

mutation CreateMetric(
  $datasetId: UUID!
  $metric: JSON!
) {
  createMetric(
    datasetId: $datasetId
    metric: $metric
  ) {
    success
    code
    error
  }
}

mutation UpdateMetric(
  $datasetId: UUID!
  $metric: JSON!
) {
  updateMetric(
    datasetId: $datasetId
    metric: $metric
  ) {
    success
    code
    error
  }
}

mutation DeleteMetric(
  $datasetId: UUID!
  $metricId: String!
) {
  deleteMetric(
    datasetId: $datasetId
    metricId: $metricId
  ) {
    success
    code
    error
  }
}
