query GetGroundedValue(
  $datasetId: UUID!
  $value: String!
  $domainEntity: String
  $copilotId: UUID
) {
  getGroundedValue(
    datasetId: $datasetId
    value: $value
    domainEntity: $domainEntity
    copilotId: $copilotId
  ) {
    matchedValue
    matchQuality
    matchType
    mappedIndicator
    mappedValue
    preferred
    domainEntity
    otherMatches
  }
}

mutation CreateDimension(
  $datasetId: UUID!
  $dimension: JSON!
) {
  createDimension(
    datasetId: $datasetId
    dimension: $dimension
  ) {
    success
    code
    error
  }
}

mutation CreateMetric(
  $datasetId: UUID!
  $metric: JSON!
) {
  createMetric(
    datasetId: $datasetId
    metric: $metric
  ) {
    success
    code
    error
  }
}
