mutation SendEmail(
  $userIds: [UUID!]
  $groupIds: [UUID!]
  $subject: String!
  $body: String!
  $attachments: [EmailAttachment!]
) {
  sendEmail(
    userIds: $userIds
    groupIds: $groupIds
    subject: $subject
    body: $body
    attachments: $attachments
  ) {
    success
    recipientCount
    error
  }
}
