query getDynamicLayout($id: UUID!) {
  getDynamicLayout(id: $id) {
    id
    name
    layoutJson
    inputVariables {
      name
    }
  }
}

mutation GeneratePdfFromLayouts($layouts: [String!]!) {
  generatePdfFromLayouts(layouts: $layouts) {
    success
    code
    error
    pdf
  }
}