mutation UpdateLoadingMessage($answerId: UUID!, $message: String!) {
    updateLoadingMessage(answerId: $answerId, message: $message)
}

query ChatCompletion($messages: [LlmChatMessage!]!, $modelSelection: LlmModelSelection) {
    chatCompletion(messages: $messages, modelSelection: $modelSelection)
}

query NarrativeCompletion($prompt: String!, $modelSelection: LlmModelSelection) {
    narrativeCompletion(prompt: $prompt, modelSelection: $modelSelection)
}